/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicResourcesRouteImport } from './routes/public-resources'
import { Route as MembershipListRouteImport } from './routes/membership-list'
import { Route as LostWillsRouteImport } from './routes/lost-wills'
import { Route as JoinRenewRouteImport } from './routes/join-renew'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as IndexRouteImport } from './routes/index'

const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/public-resources',
  path: '/public-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipListRoute = MembershipListRouteImport.update({
  id: '/membership-list',
  path: '/membership-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LostWillsRoute = LostWillsRouteImport.update({
  id: '/lost-wills',
  path: '/lost-wills',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRenewRoute = JoinRenewRouteImport.update({
  id: '/join-renew',
  path: '/join-renew',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/join-renew': typeof JoinRenewRoute
  '/lost-wills': typeof LostWillsRoute
  '/membership-list': typeof MembershipListRoute
  '/public-resources': typeof PublicResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/join-renew': typeof JoinRenewRoute
  '/lost-wills': typeof LostWillsRoute
  '/membership-list': typeof MembershipListRoute
  '/public-resources': typeof PublicResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/committees': typeof CommitteesRoute
  '/join-renew': typeof JoinRenewRoute
  '/lost-wills': typeof LostWillsRoute
  '/membership-list': typeof MembershipListRoute
  '/public-resources': typeof PublicResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/committees'
    | '/join-renew'
    | '/lost-wills'
    | '/membership-list'
    | '/public-resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/committees'
    | '/join-renew'
    | '/lost-wills'
    | '/membership-list'
    | '/public-resources'
  id:
    | '__root__'
    | '/'
    | '/committees'
    | '/join-renew'
    | '/lost-wills'
    | '/membership-list'
    | '/public-resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitteesRoute: typeof CommitteesRoute
  JoinRenewRoute: typeof JoinRenewRoute
  LostWillsRoute: typeof LostWillsRoute
  MembershipListRoute: typeof MembershipListRoute
  PublicResourcesRoute: typeof PublicResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/public-resources': {
      id: '/public-resources'
      path: '/public-resources'
      fullPath: '/public-resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-list': {
      id: '/membership-list'
      path: '/membership-list'
      fullPath: '/membership-list'
      preLoaderRoute: typeof MembershipListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-wills': {
      id: '/lost-wills'
      path: '/lost-wills'
      fullPath: '/lost-wills'
      preLoaderRoute: typeof LostWillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-renew': {
      id: '/join-renew'
      path: '/join-renew'
      fullPath: '/join-renew'
      preLoaderRoute: typeof JoinRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitteesRoute: CommitteesRoute,
  JoinRenewRoute: JoinRenewRoute,
  LostWillsRoute: LostWillsRoute,
  MembershipListRoute: MembershipListRoute,
  PublicResourcesRoute: PublicResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
